AllCops:
  Excludes:
    - vendor/**
    - bin/**
    - db/**
    - config/**
    # tddium
    - rgloader/loader.rb
    - !ruby/regexp /.*tddium.*\.rb$/

LineLength:
  Enabled: false

Documentation:
  Enabled: false

AndOr:
  Enabled: false
